import { StyleSheet } from "@react-pdf/renderer"

// Used to style the product PDF. For supported css see: https://react-pdf.org/styling
export const pdfStyles = StyleSheet.create({
  pdfViewer: {
    width: "100%",
    height: "100vh",
    userSelect: "none",
  },
  page: {
    paddingLeft: 45,
    paddingRight: 45,
    paddingTop: 40,
    paddingBottom: 50,
    marginBottom: 0,
    fontFamily: "Inter",
    fontSize: 13,
    color: "#000",
    lineHeight: 1.5,
  },
  documentTitle: {
    fontSize: 28,
    fontWeight: "bold",
    paddingTop: 118,
    paddingBottom: 2,
    color: "#000094",
  },
  documentSubTitle: {
    fontSize: 18,
    fontWeight: "medium",
    paddingBottom: 42,
    opacity: 0.8,
  },
  section: {
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    color: "#000094",
  },
  h1: {
    fontSize: 18,
    fontWeight: "semibold",
    marginBottom: 0,
    paddingTop: 10,
    paddingBottom: 5,
    color: "#000094",
  },
  h2: {
    fontSize: 14,
    fontWeight: "medium",
    color: "#000094",
    marginBottom: 0,
    paddingTop: 8,
    paddingBottom: 4,
    opacity: 0.8,
  },
  paragraph: {
    // fontSize: 13,
    fontWeight: "normal",
    paddingBottom: 2,
  },
  listUnordered: {
    textIndent: 10,
    paddingLeft: 15,
  },
  listOrdered: {
    textIndent: 10,
    paddingLeft: 15,
  },
  footer: {
    fontSize: 12,
    textAlign: "center",
    marginTop: 0,
    paddingTop: 8,
    paddingBottom: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    opacity: 0.5,
    // borderTop: "0.25 solid #000",
    position: "absolute",
    bottom: 20,
    left: 45,
    right: 45,
  },
  centerItems: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  inlineItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingRight: 10,
  },
  inlineIcon: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingRight: 10,
    alignItems: "center",
  },
  numberSection: {
    position: "absolute",
    left: -2,
    // paddingTop: 2,
    paddingRight: 10,
    marginLeft: -20,
    fontWeight: "semibold",
    fontSize: 22,
  },
  numberParagraph: {
    position: "absolute",
    left: -2,
    paddingTop: 2,
    paddingRight: 10,
    marginLeft: -20,
    opacity: 0.5,
    textAlign: "right",
    fontSize: 10,
  },
  tocItems: {
    textDecoration: "none",
    textAlign: "left",
    fontSize: 14,
    paddingBottom: 2,
    color: "#000094",
  },
})
